In [8]:
import numpy as np
# Tính độ dài vector
def computeVectorLength(vector):
  len_of_vector = np.linalg.norm(vector)  #hàm trong numpy

  return len_of_vector

In [9]:
vector = np.array([-2, 4, 9, 21])
result = computeVectorLength([vector])
print(round(result,2))

23.28


In [10]:
# Tích vô hướng
import numpy as np
def computeDotProduct(vector1, vector2):
  result = np.dot(vector1, vector2)

  return result

In [11]:
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = computeDotProduct(v1, v2)

print(round(result,2))

4


In [13]:
# Nhân vector với matrận
import numpy as np
def matrix_multi_vector(matrix, vector):
  result = np.dot(matrix, vector)
  return result

In [14]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [15]:
# Nhân ma trận với matrận
import numpy as np
def matrix_multi_matrix(matrix1, matrix2):
  result = np.dot(matrix1, matrix2)
  return result

In [16]:
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3],[6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [17]:
# Ma trận nghịch đảo
import numpy as np
def inverse_matrix(matrix):
  result = np.linalg.inv(matrix)
  return result

In [18]:
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [19]:
# Eigenvector
import numpy as np
def compute_eigenvalues_eigenvectors(matrix):
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  return eigenvalues,eigenvectors

In [20]:
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [21]:
# EigenValue
import numpy as np
from numpy import dot
from numpy.linalg import norm

def compute_cosine(v1, v2):
  cos_sim = computeDotProduct(v1,v2) / (computeVectorLength(v1)*computeVectorLength(v2))

  return cos_sim

In [22]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))

0.577
